Repository AY2122S1-CS2113T-W12-3/tp, pull requests merged in 2021-11, with the labels that each got.

#187 Update AddParser and split AddCommand for more OOP
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/DoneUndoCommand.java
  src/main/java/seedu/duke/commands/addcommands/AddEventCommand.java
  src/main/java/seedu/duke/commands/addcommands/AddMemberCommand.java
  src/main/java/seedu/duke/commands/addcommands/AddTaskCommand.java
  src/main/java/seedu/duke/items/Item.java
  src/main/java/seedu/duke/items/characteristics/Member.java
  src/main/java/seedu/duke/items/mainlists/EventCatalog.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/commandparser/AddParser.java
  src/test/java/seedu/duke/commands/AddCommandTest.java
Labels: priority.High, type.Task

#193 Update DoneUndoParser and DoneUndoCommand
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/commands/DoneUndoCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/commandparser/DoneUndoParser.java
  src/main/java/seedu/duke/parser/commandparser/DoneUndoneParser.java
Labels: priority.High, type.Task

#199 Update DG - `save` and `load` functionaltiy
  docs/DeveloperGuide.md
  docs/diagrams/LoadDiagram.puml
  docs/diagrams/SaveDiagram.puml
  docs/images/LoadDiagram.png
  docs/images/SaveDiagram.png
  src/main/java/seedu/duke/storage/StorageFile.java
Labels: type.Task

#198 PPP - crabnuggets
  docs/AboutUs.md
  docs/images/AlvinPangProfilePic.jpg
  docs/team/crabnuggets.md
Labels: type.Task

#196 Added the ability to display calendar with the date of the event highlighted
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/commands/NextCommand.java
  src/main/java/seedu/duke/parser/commandparser/ListParser.java
Labels: type.Enhancement, priority.Medium

#205 Add JUnit Tests for AddCommand and DoneUndoCommand
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/commandparser/AddParser.java
  src/test/java/seedu/duke/commands/AddCommandTest.java
  src/test/java/seedu/duke/commands/DoneUndoCommandTest.java
Labels: type.Task, priority.Medium, type.Bug

#211 V2.1 Bug fixes
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/commands/DoneUndoCommand.java
  src/main/java/seedu/duke/commands/addcommands/AddTaskCommand.java
  src/main/java/seedu/duke/items/Event.java
  src/main/java/seedu/duke/items/Task.java
  src/main/java/seedu/duke/items/characteristics/Member.java
  src/main/java/seedu/duke/parser/MemberParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/commandparser/AddParser.java
  src/main/java/seedu/duke/parser/commandparser/DoneUndoParser.java
  src/main/java/seedu/duke/parser/commandparser/NextParser.java
  src/main/java/seedu/duke/parser/commandparser/UpdateParser.java
  src/test/java/seedu/duke/commands/DoneUndoCommandTest.java
Labels: priority.High, type.Task, type.Bug

#214 Update DG - Acknowledgements and User Stories
  docs/DeveloperGuide.md
  docs/diagrams/LoadDiagram.puml
  docs/images/LoadDiagram.png
Labels: type.Task

#215 Update UG and DG for AddCommand and DoneUndoCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddDiagram.puml
  docs/diagrams/DoneUndoDiagram.puml
  docs/images/AddDiagram.png
  docs/images/DoneUndoDiagram.png
Labels: priority.High, type.Task

#218 Add PPP documentation
  docs/AboutUs.md
  docs/images/AlvinLimProfilePic.jpg
  docs/team/alvinlj00.md
  docs/team/johndoe.md
Labels: priority.High, type.Task

#223 Fix AboutUs Page
  docs/AboutUs.md
Labels: type.Bug, severity.High
